export interface Service {
  slug: string;
  title: string;
  description: string;
  longDescription: string;
  features: string[];
  icon?: string;
}

export const services: Service[] = [
  {
    slug: 'weddings',
    title: 'Weddings',
    description: 'Elevate your special day with exquisite cuisine',
    longDescription: 'At Urban Catering, we understand that your wedding day is one of the most important days of your life. Our expert team is dedicated to creating a memorable culinary experience that perfectly complements your celebration of love.',
    features: [
      'Customized menu planning',
      'Professional service staff',
      'Elegant table settings and decor',
      'Bar service options',
      'Dietary accommodation (vegetarian, vegan, gluten-free)',
      'Cake cutting and dessert service',
      'Plated dinner service',
      'Buffet style options',
      'Family style serving',
      'Cocktail reception packages',
    ],
  },
  {
    slug: 'corporate-catering',
    title: 'Corporate Catering',
    description: 'Professional catering solutions for business events',
    longDescription: 'Urban Catering provides exceptional food and service for all types of corporate events. From business meetings to company celebrations, we deliver quality catering that meets your professional standards.',
    features: [
      'Business meetings and conferences',
      'Corporate celebrations and team events',
      'Product launches and presentations',
      'Executive lunches and dinners',
      'Corporate breakfast catering',
      'Office catering and delivery',
      'Buffet-style catering',
      'Finger food and canapés',
      'Seated multi-course meals',
      'Beverages and bar service',
    ],
  },
  {
    slug: 'bbq',
    title: 'BBQ Catering',
    description: 'Authentic grilled flavors for any occasion',
    longDescription: 'Our BBQ catering service brings the smoky, savory flavors of authentic grilling to your event. Perfect for casual gatherings, summer parties, and outdoor celebrations.',
    features: [
      'Traditional charcoal grilling',
      'Premium meat selection',
      'Vegetarian BBQ options',
      'Fresh salads and sides',
      'On-site BBQ station setup',
      'Experienced BBQ chefs',
      'All equipment provided',
      'Flexible portion sizes',
    ],
  },
  {
    slug: 'cocktail-bar',
    title: 'Cocktail Bar',
    description: 'Craft cocktails and premium beverages',
    longDescription: 'Elevate your event with our professional cocktail bar service. Our expert mixologists create signature drinks and classic cocktails that impress your guests.',
    features: [
      'Professional mixologists',
      'Signature cocktail creation',
      'Premium spirits and ingredients',
      'Custom drink menus',
      'Elegant bar setup',
      'Glassware and bar tools',
      'Non-alcoholic options',
      'Responsible service',
    ],
  },
  {
    slug: 'candy-bar',
    title: 'Candy Bar',
    description: 'Sweet treats and dessert displays',
    longDescription: 'Add a touch of sweetness to your event with our delightful candy bar service. Perfect for weddings, birthdays, and celebrations of all kinds.',
    features: [
      'Wide variety of candies',
      'Custom themed displays',
      'Elegant glass containers',
      'Scoops and serving accessories',
      'Take-home favor boxes',
      'Dietary-friendly options',
      'Seasonal selections',
      'Personalized labels',
    ],
  },
  {
    slug: 'coffee',
    title: 'Coffee Service',
    description: 'Premium coffee and espresso drinks',
    longDescription: 'Keep your guests energized with our professional coffee service. From morning meetings to evening events, we serve exceptional quality coffee.',
    features: [
      'Professional baristas',
      'Espresso-based drinks',
      'Freshly brewed coffee',
      'Specialty lattes and cappuccinos',
      'Coffee station setup',
      'Premium beans selection',
      'Alternative milk options',
      'Pastries and cookies',
    ],
  },
  {
    slug: 'equipment-rentals',
    title: 'Equipment Rentals',
    description: 'Complete event equipment solutions',
    longDescription: 'We provide all the equipment you need for a successful event. From tables and chairs to lighting and sound systems, we have everything covered.',
    features: [
      'Tables and chairs',
      'Linens and tableware',
      'Tents and canopies',
      'Lighting equipment',
      'Sound systems',
      'Food stations',
      'Buffet equipment',
      'Delivery and setup',
    ],
  },
  {
    slug: 'kids-parties',
    title: 'Kids Parties',
    description: 'Fun and delicious catering for children',
    longDescription: 'Make your child\'s party unforgettable with our kid-friendly catering service. We create menus that children love while maintaining our quality standards.',
    features: [
      'Kid-friendly menus',
      'Fun food presentation',
      'Birthday cake options',
      'Themed party setups',
      'Allergy-aware preparation',
      'Healthy options available',
      'Finger foods and snacks',
      'Beverage packages',
    ],
  },
  {
    slug: 'outdoor-catering',
    title: 'Outdoor Catering',
    description: 'Exceptional dining in any location',
    longDescription: 'From garden parties to beach celebrations, we specialize in outdoor catering that adapts to any location while maintaining food quality and service excellence.',
    features: [
      'Any location service',
      'Weather contingency planning',
      'Outdoor cooking equipment',
      'Picnic-style setups',
      'Beachside catering',
      'Garden party service',
      'Mobile kitchens',
      'Sustainable practices',
    ],
  },
  {
    slug: 'private-chef',
    title: 'Private Chef Service',
    description: 'Personalized culinary experiences at home',
    longDescription: 'Enjoy restaurant-quality dining in the comfort of your home with our private chef service. Perfect for intimate dinners and special occasions.',
    features: [
      'Experienced private chefs',
      'Custom menu creation',
      'In-home meal preparation',
      'Dietary accommodations',
      'Table service included',
      'Kitchen cleanup provided',
      'Multi-course menus',
      'Wine pairing available',
    ],
  },
  {
    slug: 'private-parties',
    title: 'Private Parties',
    description: 'Exclusive catering for personal celebrations',
    longDescription: 'Celebrate life\'s special moments with our private party catering. From anniversaries to milestones, we create unforgettable dining experiences.',
    features: [
      'Customized party planning',
      'Flexible menu options',
      'Intimate gatherings',
      'Large celebrations',
      'Theme coordination',
      'Decor assistance',
      'Full-service staff',
      'Event timelines managed',
    ],
  },
  {
    slug: 'christenings',
    title: 'Christenings',
    description: 'Graceful catering for baptism celebrations',
    longDescription: 'Mark this sacred occasion with beautiful food and gracious service. Our christening catering adds elegance to your family\'s special day.',
    features: [
      'Elegant buffet options',
      'Finger food selections',
      'Celebratory cakes',
      'Child-friendly menu',
      'Beverage service',
      'Table decorations',
      'Conservative portions',
      'Traditional & modern options',
    ],
  },
];
